Algoritmo "exemplo repita"
// Disciplina   : [ Lógica de Programação]
// Professor   : Jailson 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/09/2023
Var
// Seção de Declarações das variáveis 
contadora:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
repita
 escreval("Jailson", contadora)
 contadora <- contadora + 1
 ate contadora = 10

Fimalgoritmo
