Algoritmo "exemplo enquanto"
// Disciplina   : [ Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/09/2023
Var
   // Seção de Declarações das variáveis
   contador:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   enquanto contador<8 faca
      escreval("Jailson")
      contador <- contador+1
   fimenquanto

Fimalgoritmo